sudo: false
language: rust
matrix:
  include:
    - os: linux
      rust: stable

    - os: linux
      rust: nightly
      addons:
        apt:  
          sources:
            - sourceline: 'deb http://deb.debian.org/debian sid main'
          packages:
            - grcov

script:
    - |
      if [ "$TRAVIS_RUST_VERSION" = "nightly" ] && [ -z "$TRAVIS_TAG" ]; then
        export CARGO_INCREMENTAL=0;
        export RUSTFLAGS="-Zprofile -Ccodegen-units=1";
      fi
    - if [ "$TRAVIS_TAG" ]; then export CARGO_OPTIONS="--release"; fi
    - cargo build --verbose $CARGO_OPTIONS
    - cargo test --verbose $CARGO_OPTIONS
    - |
      if [ "$TRAVIS_RUST_VERSION" = "nightly" ] && [ -z "$TRAVIS_TAG" ]; then
        zip -0 ccov.zip `find . \( -name "rust_parsepatch*.gc*" \) -print`;
        grcov ccov.zip -s . -t lcov --llvm --branch --ignore-not-existing --ignore-dir "/*" > lcov.info;
        bash <(curl -s https://codecov.io/bash) -f lcov.info;
      fi
